/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function test(): Array<Array<string>>
export type NodeExec = Execution
export class Execution {
  constructor()
  query(query: string): Array<Record<string,string>>
}
